name: AkitaRTM Test

on: push

jobs:
  compile:
    name: Compile AkitaRTM
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        working-directory: ./monitoring/web
        run: npm install

      - name: Build
        working-directory: ./monitoring/web
        run: npm run build
